### ISSUE TITLE
nginx-ingress v0.42.0 发布了

### ISSUE THREAD

**Issue by zhangsean** [zhigang/k8s-nginx-ingress-controller#1]
[nginx-ingress v0.42.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.42.0) 发布了.

顺便请教，你是怎么保持版本及时跟随原项目更新的？

**Comment by zhigang** [comment]
目前都是手动维护，跟踪原项目的发版，所以有时候不能很及时的更新。
v0.42.0已经同步好了哈。

**Comment by zhangsean** [comment]
[v0.43.0 ](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.43.0) 也发布了。。。
用Github Actions可以实现自动检测源项目发布并自动更新Dockerfile，从而自动及时跟进源项目发布。
可以参考我的 https://github.com/zhangsean/k8s-descheduler-mirror

**Comment by zhigang** [comment]
这个不错，有空我也搞一下，3Q!
